spring.application.name=FundooNotesApp
spring.datasource.url=jdbc:mysql://localhost:3306/fundoo_notes
spring.datasource.username=root
spring.datasource.password=PassWord

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ActiveMQ (JMS) Configuration
spring.activemq.in-memory=true
spring.jms.pub-sub-domain=false

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Spring Batch Configuration (Export On-Demand)
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# SMTP Mail Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anujvishwakarma9827@gmail.com
spring.mail.password=xswrjzpqcuyrriql
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true