server:
  port: 8083

spring:
  application:
    name: reminder-service

  activemq:
    in-memory: true

  jms:
    pub-sub-domain: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: anujvishwakarma9827@gmail.com
    password: xswrjzpqcuyrriql
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
